MODEL_PATH = 'src/models/hand_landmarker.task'

EXIT_KEY_CODE = 27

INDEX_FINGER_TIP_LANDMARKER_INDEX = 8
MIDDLE_FINGER_TIP_LANDMARKER_INDEX = 12
RING_FINGER_TIP_LANDMARKER_INDEX = 16

WEBCAM_INDEX = 2
